### ISSUE TITLE
Is the 3D demo publicly available?

### ISSUE THREAD

**Issue by burlachenkok** [cvxgrp/fastpathplanning#4]
I am curious. Is the source code for this demo publicly available?
https://www.youtube.com/watch?v=p1xlcNiER0o&ab_channel=RobotLocomotionGroup

The link to the video is provided here:
https://stanford.edu/~boyd/papers/fpp.html

**Comment by TobiaMarcucci** [comment]
I've just added the UAV demo to the examples folder. Note that the 3D visualization of the UAV requires [meshcat](https://github.com/rdeits/meshcat-python). Note also that I've reduced the size of the environment with respect to the example in the paper so that the preprocessing works fine also with Clarabel. If you'd like to try larger environments, I suggest you use Mosek as a solver for the optimization of the representative points during the offline preprocessing.
